### ISSUE TITLE
snmptt configuration

### ISSUE THREAD

**Issue by rklomp** [blka/zabbix-3.0#1]
Can you share how you configured snmptt to get the traps working?

@masterdead @blka

**Comment by blka** [comment]
Here you go
https://techdocs.f5.com/kb/en-us/archived_products/big-ip/manuals/product/bigip2_1/bigip_sn.html


W dniu czw., 19.12.2019 o 11:07 René Klomp <notifications@github.com>
napisał(a):

**Comment by rklomp** [comment]
Thanks for your quick reply.
This documentation is for configuring sending the traps on the F5 itself. I am looking for an example how to configure snmptrapd and snmptt on the zabbix server to get all the traps to the snmptrap[F5-BIGIP-COMMON-MIB] item in the zabbix template.

**Comment by masterdead** [comment]
@rklomp Hi, we are currently working on it
